# Generated by Django 4.0.4 on 2022-06-17 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_document_created_at_alter_document_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='file_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='File size'),
        ),
    ]
