# Generated by Django 4.0.4 on 2022-06-17 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_information_file_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='file_size',
        ),
    ]
