# Generated by Django 4.0.4 on 2022-06-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_remove_information_file_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='File size'),
        ),
        migrations.AddField(
            model_name='file',
            name='file_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='File size'),
        ),
    ]
