# Generated by Django 4.0.4 on 2022-10-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_document_file_size_alter_file_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='image',
            field=models.ImageField(upload_to='images/', verbose_name='Cover'),
        ),
    ]
