# Generated by Django 4.0.4 on 2022-12-23 10:37

from django.db import migrations
import pages.fields
import pages.yandex_s3_storage


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_alter_tutorial_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=pages.fields.PrivateFileField(storage=pages.yandex_s3_storage.PrivateClientUserContentStorage(), upload_to='Documents', validators=[pages.fields.validate_file_size], verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=pages.fields.PrivateFileField(storage=pages.yandex_s3_storage.PrivateClientUserContentStorage(), upload_to='Files', validators=[pages.fields.validate_file_size], verbose_name='File'),
        ),
    ]
