# Generated by Django 4.0.4 on 2022-10-07 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_customuser_is_staff'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserUuid',
            new_name='EmailVerificationToken',
        ),
    ]
