# Generated by Django 4.0.4 on 2022-11-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0002_alter_company_created_at_alter_company_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='max_num_company_users',
            field=models.PositiveSmallIntegerField(default=20, verbose_name='Company Users Limit'),
        ),
    ]
