# Generated by Django 4.0.4 on 2022-10-20 13:37

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer_dashboard', '0002_alter_company_created_at_alter_company_updated_at'),
        ('users', '0015_alter_emailverificationtoken_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('to_email', models.BooleanField(verbose_name='Send by email')),
                ('is_read', models.BooleanField(default=False, verbose_name='is_read')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_notifications', to='users.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('subject', models.CharField(max_length=250, verbose_name='Subject')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Text')),
                ('company', models.ManyToManyField(blank=True, to='customer_dashboard.company', verbose_name='Companies')),
                ('company_types', models.ManyToManyField(blank=True, to='customer_dashboard.companytype', verbose_name='Companies Types')),
                ('notification_options', models.ManyToManyField(blank=True, related_name='notifications_options', to='notifications.notificationoptions', verbose_name='user_profile')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
