# Generated by Django 4.0.4 on 2022-10-20 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_emailverificationtoken_options_and_more'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_options',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='notifications.notificationoptions', verbose_name='user_profile'),
        ),
        migrations.AlterField(
            model_name='notificationoptions',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.userprofile'),
        ),
    ]
