# Generated by Django 4.0.4 on 2022-10-20 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_options',
        ),
        migrations.AddField(
            model_name='notificationoptions',
            name='notification',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notification', verbose_name='notifications'),
            preserve_default=False,
        ),
    ]
