# Generated by Django 4.0.4 on 2022-10-20 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_emailverificationtoken_options_and_more'),
        ('notifications', '0003_remove_notification_notification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationoptions',
            name='to_email',
        ),
        migrations.AddField(
            model_name='notification',
            name='to_email',
            field=models.BooleanField(default=1, verbose_name='Send by email'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='notificationoptions',
            name='notification',
        ),
        migrations.AddField(
            model_name='notificationoptions',
            name='notification',
            field=models.ManyToManyField(blank=True, related_name='notifications', to='notifications.notification', verbose_name='notifications_options'),
        ),
        migrations.RemoveField(
            model_name='notificationoptions',
            name='profile',
        ),
        migrations.AddField(
            model_name='notificationoptions',
            name='profile',
            field=models.ManyToManyField(related_name='notifications', to='users.userprofile'),
        ),
    ]
