# Generated by Django 4.0.4 on 2022-10-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_dashboard', '0002_alter_company_created_at_alter_company_updated_at'),
        ('notifications', '0004_remove_notificationoptions_to_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='company',
            field=models.ManyToManyField(to='customer_dashboard.company', verbose_name='Companies'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='company_types',
            field=models.ManyToManyField(to='customer_dashboard.companytype', verbose_name='Companies Types'),
        ),
    ]
