# Generated by Django 4.0.4 on 2022-10-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_emailverificationtoken_options_and_more'),
        ('notifications', '0006_alter_notification_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='is_read')),
                ('is_delete', models.BooleanField(default=False, verbose_name='is_delete')),
                ('notification', models.ManyToManyField(blank=True, related_name='notifications', to='notifications.notification', verbose_name='Notifications')),
                ('profile', models.ManyToManyField(to='users.userprofile')),
            ],
        ),
        migrations.DeleteModel(
            name='NotificationOptions',
        ),
    ]
