# Generated by Django 4.0.4 on 2022-10-21 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_alter_emailverificationtoken_options_and_more'),
        ('notifications', '0007_notificationinstance_delete_notificationoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationinstance',
            name='notification',
        ),
        migrations.AddField(
            model_name='notificationinstance',
            name='notification',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='notifications.notification', verbose_name='Notifications'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='notificationinstance',
            name='profile',
        ),
        migrations.AddField(
            model_name='notificationinstance',
            name='profile',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile'),
            preserve_default=False,
        ),
    ]
