# Generated by Django 4.0.4 on 2022-10-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_remove_notificationinstance_notification_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ('-created_at',), 'verbose_name': 'Notification', 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AlterModelOptions(
            name='notificationinstance',
            options={'verbose_name': 'Notification Instance', 'verbose_name_plural': 'Notifications Instances'},
        ),
        migrations.RemoveField(
            model_name='notificationinstance',
            name='is_delete',
        ),
    ]
